
POST http://localhost:3000/login
Content-Type: application/json

{
	"id": "student",
	"password": "student"
}

### ALL COURSES

GET http://localhost:3000/courses

### ALL COURSES OF GUARANTOR

GET http://localhost:3000/courses?guarantor=svetr00

### ONE COURSE

GET http://localhost:3000/courses/ITU

### ALL ROOM

GET http://localhost:3000/rooms

### ONE ROOM

GET http://localhost:3000/rooms/A101

### ALL USERS

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q

### ONE USER

GET http://localhost:3000/users/svetr00
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q

### GET REGISTERED COURSES OF STUDENT

GET http://localhost:3000/registrations/courses/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0dWRlbnQiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTcwMTA1ODg2MH0.-4wP0rK_pf1sfMW9t8uqGVKbHv61po5O7xBlC0pD308

### GET COURSES OF STUDENT WITH REG DATA

GET http://localhost:3000/registrations/courses/student/reg_data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0dWRlbnQiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTcwMTA1ODg2MH0.-4wP0rK_pf1sfMW9t8uqGVKbHv61po5O7xBlC0pD308

### GET REGISTERED INSTANCES OF STUDENT

GET http://localhost:3000/registrations/instances/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q

### GET INSTANCES OF STUDENT WITH REG DATA

GET http://localhost:3000/registrations/instances/student/reg_data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0dWRlbnQiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTcwMTA1ODg2MH0.-4wP0rK_pf1sfMW9t8uqGVKbHv61po5O7xBlC0pD308

### ALL REGISTRATION

GET http://localhost:3000/registrations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q

### GET STATE OF ACTIVE REGISTRATION

GET http://localhost:3000/registrations/active
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q

### START COURSES REGISTRATIONS

PUT http://localhost:3000/registrations/start/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q
Content-Type: application/json

{
	"type": "COURSES"
}

### STOP COURSES REGISTRATIONS

PUT http://localhost:3000/registrations/stop/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q
Content-Type: application/json

{
	"type": "COURSES"
}

### START INSTANCE REGISTRATIONS

PUT http://localhost:3000/registrations/start/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q
Content-Type: application/json

{
	"type": "INSTANCES"
}

### STOP INSTANCE REGISTRATIONS

PUT http://localhost:3000/registrations/stop/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q
Content-Type: application/json

{
	"type": "INSTANCES"
}

### REGISTER COURSE

POST http://localhost:3000/registrations/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q
Content-Type: application/json

{
	"course": "IMA2",
	"student": "student"
}

### UNREGISTER COURSE

DELETE  http://localhost:3000/registrations/courses/IMA2/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q

### REGISTER INSTANCE

POST http://localhost:3000/registrations/instances
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q
Content-Type: application/json

{
	"instance": 1,
	"student": "student",
	"order": 1
}

### UNREGISTER INSTANCE

DELETE  http://localhost:3000/registrations/instances/1/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI4MDIwfQ.0xYjsY4R2s0LICticE_Xvaer-QaBRxzKXcmAEzQZd9Q

### GET ALL INSTANCES

GET http://localhost:3000/courses/instances

### GET ALL INSTANCES OF A LECTURER

GET http://localhost:3000/courses/instances?lecturer=garant

### GET ALL LECTURERS OF AN ACTIVITY

GET http://localhost:3000/courses/ITU/activities/1/lecturers